# Generated by Django 4.0.6 on 2022-07-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AD', 'Admin'), ('ST', 'Staff'), ('US', 'User')], default='US', max_length=2, null=True),
        ),
    ]
