# Generated by Django 4.0.6 on 2022-07-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_remove_package_year_in_school_alter_package_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2),
        ),
    ]
