# Generated by Django 4.0.6 on 2022-07-18 14:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_remove_package_year_in_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='id',
        ),
        migrations.AlterField(
            model_name='package',
            name='package_ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
