# Generated by Django 4.0.6 on 2022-07-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_year_in_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='year_in_school',
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('RE', 'Recieved'), ('DI', 'Delivered')], default='DI', max_length=2),
        ),
    ]
