# Generated by Django 4.0.6 on 2022-07-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_alter_package_carrier_alter_package_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='carrier',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='package',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='package',
            name='reciever_initial',
            field=models.TextField(default='', max_length=3),
        ),
    ]
