# Generated by Django 4.0.6 on 2022-07-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0010_alter_package_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='upload',
            field=models.ImageField(null=True, upload_to='uploads/% Y/% m/% d/'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='package',
            name='pic',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
