# Generated by Django 4.0.6 on 2022-07-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0013_remove_package_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='building',
            field=models.TextField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='weekday',
            field=models.TextField(max_length=3, null=True),
        ),
    ]
