# Generated by Django 4.0.6 on 2022-07-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0014_package_building_package_order_package_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='tracking_number',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='TrackNum',
        ),
    ]
