# Generated by Django 4.0.6 on 2022-07-19 00:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True, max_length=20, null=True)),
                ('middle_name', models.TextField(blank=True, max_length=20, null=True)),
                ('last_name', models.TextField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password', models.TextField(default='')),
                ('building', models.TextField(default='')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.name')),
            ],
        ),
    ]
